
services:
  postgres:
    image: postgres:15-alpine
    container_name: dora-metrics-db
    environment:
      POSTGRES_USER: dora
      POSTGRES_PASSWORD: dora_password
      POSTGRES_DB: dora_metrics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dora"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dora-metrics-backend
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://dora:dora_password@postgres:5432/dora_metrics
      PORT: 3000
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: dora-metrics-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3001

volumes:
  postgres_data:
